; ==============================================================================
; Project      : ESP32-S3 BOOT Interrupt BLE HID
; Workspace    : ESP32S3_Boot_BLE_HID_PIO
; Framework    : Arduino on ESP32-S3
; HID Library  : HijelHID_BLEKeyboard
; ==============================================================================
;
; MODO NORMAL / SEM DEBUG
; ------------------------------------------------------------------------------
; Upload:
;   Porta USB-UART CH343
;   Porta Windows: COM12
;
; Build:
;   PlatformIO: Build
;   Atalho VS Code: Ctrl + Alt + B
;
; Upload:
;   PlatformIO: Upload
;   Atalho VS Code: Ctrl + Alt + U
;
; Terminal:
;   pio run -e esp32s3_uart
;   pio run -e esp32s3_uart -t upload
;
; Bibliotecas:
;   - Adafruit NeoPixel via lib_deps
;   - HijelHID_BLEKeyboard via Arduino libraries folder
;
; ATENÇÃO:
;   Este INI não usa debug_tool.
;   Este INI não usa COM13.
;   Este INI não usa USB-JTAG.
;   Este INI usa somente COM12 para gravação normal.
;
; ==============================================================================

[platformio]
default_envs = esp32s3_uart


[env:esp32s3_uart]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM12
monitor_port = COM12

upload_speed = 460800
monitor_speed = 115200

lib_extra_dirs =
    C:/Users/mlevi/Documents/Arduino/libraries

lib_deps =
    adafruit/Adafruit NeoPixel